linuxdeepin/deepin-ai-daemon

README.zh_CN.md

doc: remove unused link in readme.zh_cn

---

README.md

doc: remove content in readme

---

src/server/analyzeserverdbus.cpp

fix the warning

---

src/parser/audiopropertyparser.cpp

fix issue of unable to search for music by author

---

README.zh_CN.md

doc: remove incorrect link in readme

---

debian/control

add deepin-ai-models in control
Log:

feat: add depend in control

---

src/parser/imagepropertyparser.cpp

ocr takes up a lot of content when parsing high-resolution images
Log: fix bug
Bug: https://pms.uniontech.com/bug-view-220533.html

fix: High memory usage

---

src/main.cpp
src/monitor/filemonitor.cpp
src/monitor/filemonitor.h

as title
Log: Deferred index creation：

chore: Deferred index creation

---

src/parser/imagepropertyparser.cpp

fix: Image is blurred after being scaled

---

assets/icon/deepin-ai-daemon.svg
src/CMakeLists.txt

chore: add icon

---

src/index/indexworker.cpp
src/main.cpp
src/utils/resourcemanager.cpp
src/utils/resourcemanager.h

1.as title
2.Auto-release memory
Log: new feature

feat: New Resource Management module

---

.gitmodules
.reuse/dep5
3rdparty/CMakeLists.txt
CMakeLists.txt
assets/dbus/org.deepin.ai.daemon.VectorIndex.xml
src/CMakeLists.txt
src/index/embeddingworker.cpp
src/index/embeddingworker.h
src/index/vectorindex/embedding.cpp
src/index/vectorindex/embedding.h
src/modelhub/modelhubwrapper.cpp
src/modelhub/modelhubwrapper.h
src/server/analyzeserver.cpp
src/server/vectorindexdbus.cpp
src/server/vectorindexdbus.h

pull faiss and add modelhub wrapper
Log: 
Task:
Influence:

feat: pull faiss and add modelhub wrapper

---

src/modelhub/modelhubwrapper.cpp
src/modelhub/modelhubwrapper.h

Starting without detached may cause model loading to freeze.
Log: 
Task:
Influence:

fix: Starting the modelhub detached

---

assets/dbus/org.deepin.ai.daemon.VectorIndex.xml
debian/control
src/database/embeddatabase.cpp
src/database/embeddatabase.h
src/index/embeddingworker.cpp
src/index/embeddingworker.h
src/index/global_define.h
src/index/private/embeddingworker_p.h
src/index/vectorindex/embedding.cpp
src/index/vectorindex/embedding.h
src/index/vectorindex/vectorindex.cpp
src/index/vectorindex/vectorindex.h
src/server/vectorindexdbus.cpp
src/server/vectorindexdbus.h

1.add interface.
2.process bugs
Log:
Task:

feat: Add some interfaces and process bugs

---

debian/control

feat: add build-depend

---

debian/control
src/index/embeddingworker.cpp
src/index/vectorindex/embedding.cpp

delete deepin-ai-model depend.
Log:
Task:

feat: delete deepin-ai-model depend

---

assets/dbus/org.deepin.ai.daemon.VectorIndex.xml
src/index/embeddingworker.cpp
src/index/embeddingworker.h
src/index/private/embeddingworker_p.h
src/index/vectorindex/vectorindex.cpp
src/server/vectorindexdbus.cpp
src/server/vectorindexdbus.h

1.add interface for getting doc file paths;
2.solving some bugs.
Log:
Task:

feat: add get doc files interface

---

src/index/embeddingworker.cpp
src/index/embeddingworker.h
src/server/vectorindexdbus.cpp
src/server/vectorindexdbus.h

1.add index create signal;
2.async call index create interface;
Log:
Task:

feat: add index create signal

---

src/index/embeddingworker.cpp
src/index/embeddingworker.h
src/index/vectorindex/embedding.cpp
src/index/vectorindex/embedding.h
src/index/vectorindex/vectorindex.cpp

fix: Solving some bugs

---

assets/dbus/org.deepin.ai.daemon.VectorIndex.xml
src/index/embeddingworker.cpp
src/index/embeddingworker.h
src/server/vectorindexdbus.cpp
src/server/vectorindexdbus.h

创建/更新索引时增加文件列表参数
增加索引删除dbus信号
Log:索引变化信号调整

feat: 索引变化信号调整

---

src/database/embeddatabase.cpp
src/database/embeddatabase.h
src/index/global_define.h
src/index/vectorindex/embedding.cpp
src/index/vectorindex/vectorindex.cpp

add system assistant process.
Log:
Task:

feat: add system assistant process

---

src/index/vectorindex/embedding.cpp
src/index/vectorindex/embedding.h

feat: solving some bugs

---

assets/dbus/org.deepin.ai.daemon.AnalyzeServer.xml
assets/dbus/org.deepin.ai.daemon.VectorIndex.xml
src/modelhub/modelhubwrapper.cpp
src/modelhub/modelhubwrapper.h
src/server/analyzeserverdbus.cpp
src/server/analyzeserverdbus.h
src/server/vectorindexdbus.cpp
src/server/vectorindexdbus.h

feat:  add auto index interface

---

assets/dbus/org.deepin.ai.daemon.VectorIndex.xml
src/config/configmanager.cpp
src/config/configmanager.h
src/database/embeddatabase.cpp
src/database/embeddatabase.h
src/index/embeddingworker.cpp
src/index/embeddingworker.h
src/index/global_define.h
src/index/indexmanager.cpp
src/index/indexmanager.h
src/index/private/embeddingworker_p.h
src/index/vectorindex/embedding.cpp
src/index/vectorindex/embedding.h
src/index/vectorindex/vectorindex.cpp
src/index/vectorindex/vectorindex.h
src/main.cpp
src/monitor/filemonitor.cpp
src/server/vectorindexdbus.cpp
src/server/vectorindexdbus.h

Index building strategy adjustment
Log:
Task:

feat: Index building strategy adjustment

---

assets/dbus/org.deepin.ai.daemon.VectorIndex.xml
src/index/embeddingworker.cpp
src/index/embeddingworker.h
src/index/vectorindex/vectorindex.cpp
src/server/vectorindexdbus.cpp
src/server/vectorindexdbus.h

feat: add new interface

---

src/index/vectorindex/embedding.cpp

solving text chunk limit exceeded.
Log:
Task:

fix: solving text chunk limit exceeded

---

src/database/embeddatabase.cpp
src/database/embeddatabase.h
src/index/embeddingworker.cpp
src/index/embeddingworker.h
src/index/private/embeddingworker_p.h
src/index/vectorindex/embedding.cpp
src/index/vectorindex/embedding.h
src/index/vectorindex/vectorindex.cpp
src/index/vectorindex/vectorindex.h
src/server/vectorindexdbus.cpp

Optimizing threading issues.
Log:

fix: Optimizing threading issues

---

src/index/embeddingworker.cpp
src/index/global_define.h
src/index/vectorindex/embedding.cpp
src/index/vectorindex/embedding.h
src/index/vectorindex/vectorindex.cpp

solving chunk exceed length.
Log:
Task:

fix: chunk length

---

src/config/configmanager.cpp
src/index/embeddingworker.cpp
src/index/private/embeddingworker_p.h
src/index/vectorindex/embedding.cpp
src/index/vectorindex/vectorindex.cpp

fix: add file filter

---

src/index/embeddingworker.cpp
src/index/vectorindex/embedding.cpp
src/index/vectorindex/embedding.h

search result error
Log:
Task:

fix: search result error

---

src/index/embeddingworker.cpp
src/index/private/embeddingworker_p.h
src/index/vectorindex/embedding.cpp
src/index/vectorindex/embedding.h
src/index/vectorindex/vectorindex.cpp
src/index/vectorindex/vectorindex.h

1.solving concurrent problem.
2.cleaning up useless code.
Log:
Task:

fix: concurrent problem

---

src/modelhub/modelhubwrapper.cpp
src/modelhub/modelhubwrapper.h

fix: add lock

---

src/index/vectorindex/vectorindex.cpp

create index id error
Log:
Task:

fix: create index id error

---

src/index/embeddingworker.cpp
src/index/embeddingworker.h
src/index/vectorindex/embedding.cpp
src/index/vectorindex/embedding.h

add getting cache docs for index.
Log:
Task:

fix: add getting cache docs for index

---

debian/control
src/CMakeLists.txt
src/index/embeddingworker.cpp
src/index/global_define.h
src/index/private/embeddingworker_p.h
src/index/vectorindex/embedding.cpp
src/index/vectorindex/embedding.h
src/server/vectorindexdbus.cpp
src/utils/utils.cpp
src/utils/utils.h

1.transfer other text encoding to utf-8.
2.add save source document.
Log:
Task: https://pms.uniontech.com/bug-view-255147.html

fix: transfer other text encoding to utf-8

---

src/index/embeddingworker.cpp
src/index/vectorindex/embedding.cpp

index file name
Log: 
Bug: https://pms.uniontech.com/bug-view-255657.html

fix: index file name

---

src/index/embeddingworker.cpp
src/index/vectorindex/embedding.cpp
src/index/vectorindex/vectorindex.cpp
src/index/vectorindex/vectorindex.h

solving index delete from bitsets
Log:
Task:

fix: index delete

---

src/index/embeddingworker.cpp
src/index/embeddingworker.h
src/index/private/embeddingworker_p.h
src/server/vectorindexdbus.cpp

add index update time
Log:
Task:

fix: add index update time

---

src/index/embeddingworker.cpp
src/index/vectorindex/embedding.cpp
src/index/vectorindex/embedding.h
src/index/vectorindex/vectorindex.cpp

some bugs.
Log:
Task: https://pms.uniontech.com/bug-view-256649.html
https://pms.uniontech.com/bug-view-256495.html
https://pms.uniontech.com/bug-view-256497.html

fix: some bugs

---

src/database/embeddatabase.cpp
src/database/embeddatabase.h
src/index/embeddingworker.cpp

fix: database error

---

src/index/embeddingworker.cpp
src/index/embeddingworker.h
src/index/private/embeddingworker_p.h
src/index/vectorindex/embedding.cpp
src/index/vectorindex/embedding.h

1.add index create status;
2.forbidding dump on index creating;
3.dumping on application quitting.
Log:
Task: https://pms.uniontech.com/bug-view-256721.html

fix: add index create status

---

src/index/embeddingworker.cpp

add support document
Log:
Task:

fix: add support document

---

src/index/embeddingworker.cpp
src/index/vectorindex/embedding.cpp
src/index/vectorindex/embedding.h
src/index/vectorindex/vectorindex.cpp
src/index/vectorindex/vectorindex.h

dump when index created
Log:
Task:

fix: dump when index created

---

src/index/embeddingworker.cpp
src/index/vectorindex/embedding.cpp

Add restrictions on creating indexes.
Log:

feat: Add restrictions on creating indexes

---

src/index/embeddingworker.cpp
src/index/vectorindex/embedding.cpp

1. copy doc after index created. 2.text chunk bug.
Log:
Task: https://pms.uniontech.com/bug-view-259117.html 
https://pms.uniontech.com/bug-view-259097.html

fix: text chunk and copy source document

---

assets/dbus/org.deepin.ai.daemon.VectorIndex.xml
src/database/embeddatabase.cpp
src/database/embeddatabase.h
src/index/embeddingworker.cpp
src/index/embeddingworker.h
src/index/global_define.h
src/index/private/embeddingworker_p.h
src/index/vectorindex/embedding.cpp
src/index/vectorindex/vectorindex.cpp
src/server/vectorindexdbus.cpp
src/server/vectorindexdbus.h

1. modify data type of DB return
2. interface getDocs return add doc content
Log:
Task: https://pms.uniontech.com/bug-view-259101.html

fix: DB return data type and modify interface

---

src/index/vectorindex/embedding.cpp
src/utils/utils.cpp
src/utils/utils.h

fix: Resolve bugs
1. Save file as readonly.
2. filterring invalid document content.
Log:
Task: https://pms.uniontech.com/bug-view-259875.html
https://pms.uniontech.com/bug-view-259873.html

fix: Save file as readonly

---

src/index/embeddingworker.cpp
src/index/embeddingworker.h
src/index/global_define.h
src/index/private/embeddingworker_p.h
src/server/vectorindexdbus.cpp

Result for creating index.
Log:
Task: https://pms.uniontech.com/bug-view-255239.html

fix: Result for creating index

---

src/server/vectorindexdbus.cpp
src/server/vectorindexdbus.h

VectorIndex Dbus start too slow
Log:
Task: https://pms.uniontech.com/bug-view-263147.html

fix: VectorIndex Dbus start too slow

---

src/index/indexmanager.cpp

Description: 开通自然语言索引，增加开启和停用的接口
Log: 开通自然语言索引，增加开启和停用的接口

feat: 开通自然语言索引，增加开启和停用的接口

---

src/monitor/filemonitor.cpp

Description: 潜在的内存引用错误，临时变量内存已释放
Log: 潜在的内存引用错误，临时变量内存已释放

fix: 潜在的内存引用错误，临时变量内存已释放

---

debian/changelog

chore:  update version
